
export const INCREMENT = 'INCREMENT'
export const DELETE_ARTICLE = 'DELETE_ARTICLE'
export const UPDATE_DATEPICKER = "UPDATE_DATEPICKER"
export const UPDATE_SELECT = "UPDATE_SELECT"
export const RESET_DATEPICKER = "RESET_DATEPICKER"
